name: we_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # for state management
  get: ^4.6.5
# for integrating firebase
  firebase_core: ^2.16.0
  # for handle google sign in
  google_sign_in: ^6.1.5
  # for handle authentication
  firebase_auth: ^4.10.0
  # to store data in cloud
  cloud_firestore: ^4.9.2
  # to store small data in local storage
  shared_preferences: ^2.2.1
  # for network image
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  # for pick image
  image_picker: ^1.0.4
  # for storing profile photo
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  http: ^1.1.0
  flutter_notification_channel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icons/icon.png"
#   min_sdk_android: 21 
#   remove_alpha_ios: true    

  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
