// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdPaCs2kXBGO_sIBZ6L6E560LTGBe7TVI',
    appId: '1:462360828977:web:017477247e48c3deeb0910',
    messagingSenderId: '462360828977',
    projectId: 'chat-2ba4b',
    authDomain: 'chat-2ba4b.firebaseapp.com',
    storageBucket: 'chat-2ba4b.appspot.com',
    measurementId: 'G-MNZCR93XGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwrQIn5gPKj77F5S5oljmDo8RwoGrJAs',
    appId: '1:462360828977:android:17347081f24e6e18eb0910',
    messagingSenderId: '462360828977',
    projectId: 'chat-2ba4b',
    storageBucket: 'chat-2ba4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEt9o-mgKPnrTBk7bQddWZKcJ_8psego0',
    appId: '1:462360828977:ios:dde8cc58ecd7322aeb0910',
    messagingSenderId: '462360828977',
    projectId: 'chat-2ba4b',
    storageBucket: 'chat-2ba4b.appspot.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEt9o-mgKPnrTBk7bQddWZKcJ_8psego0',
    appId: '1:462360828977:ios:c71cfc0d96238b03eb0910',
    messagingSenderId: '462360828977',
    projectId: 'chat-2ba4b',
    storageBucket: 'chat-2ba4b.appspot.com',
    iosBundleId: 'com.example.weChat.RunnerTests',
  );
}
